### ISSUE TITLE
ModuleNotFoundError: No module named 'groq.cloud'

### ISSUE THREAD

**Issue by bgeils** [groq/groqapi-py-sdk#3]
Attempting to run the `groq` examples on Python 3.11.3

`pip install -U groq`

Confirmed I'm on groq==0.4.0

```python
from groq.cloud.core import ChatCompletion
```

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[30], line 1
----> 1 from groq.cloud.core import ChatCompletion

ModuleNotFoundError: No module named 'groq.cloud'

**Comment by hozen-groq** [comment]
Hi, Brendon! Thanks for reaching out! Could you please try reverting back to version 0.3.0?

**Comment by bgeils** [comment]
Works now! Thanks

**Comment by hozen-groq** [comment]
Fantastic! Hope you enjoy the API! 🚀
